remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [frontend-mentor-challenges]
description: [Explore my take on Frontend Mentor challenges.]